name: Publish Regular Patch

on:
    workflow_dispatch:

#    schedule:
#        - cron: '*/77 * * * *'
#    push:
#        branches:
#            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Set up SSH
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_DPK }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/pk
                  chmod 600 ~/.ssh/pk
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
            - run: npm ci
            - run: npm run build
            - run: |
                  git config --global user.name 'Marc MOREAU'
                  git config --global user.email 'moreau.marc.web@gmail.comm'
            - run: git add . && git commit -m "clean"
            - run: npm version patch
            - name: Push changes
              run: |
                  git push origin main --follow-tags
