name: Publish Regular Patch

on:
#    schedule:
#        - cron: '0 0 * * *'
#        - cron: '44 0 * * *'
#        - cron: '28 1 * * *'
#        - cron: '12 2 * * *'
#        - cron: '56 2 * * *'
#        - cron: '40 3 * * *'
#        - cron: '24 4 * * *'
#        - cron: '8 5 * * *'
#        - cron: '52 5 * * *'
#        - cron: '36 6 * * *'
#        - cron: '20 7 * * *'
#        - cron: '4 8 * * *'
#        - cron: '48 8 * * *'
#        - cron: '32 9 * * *'
#        - cron: '16 10 * * *'
#        - cron: '0 11 * * *'
#        - cron: '44 11 * * *'
#        - cron: '28 12 * * *'
#        - cron: '12 13 * * *'
#        - cron: '56 13 * * *'
#        - cron: '40 14 * * *'
#        - cron: '24 15 * * *'
#        - cron: '8 16 * * *'
#        - cron: '52 16 * * *'
#        - cron: '36 17 * * *'
#        - cron: '20 18 * * *'
#        - cron: '4 19 * * *'
#        - cron: '48 19 * * *'
#        - cron: '32 20 * * *'
#        - cron: '16 21 * * *'
#        - cron: '0 22 * * *'
#        - cron: '44 22 * * *'
#        - cron: '28 23 * * *'
    workflow_dispatch:
#    push:
#        branches:
#            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
            - name: Set up SSH
              env:
                SSH_PRIVATE_KEY: ${{ secrets.SSH_DPK }}
              run: |
                  mkdir -p ~/.ssh
                  echo "$SSH_PRIVATE_KEY" > ~/.ssh/pk
                  chmod 600 ~/.ssh/pk
                  
                  # Start the SSH agent and add the key
                  eval "$(ssh-agent -s)"
                  ssh-add ~/.ssh/pk
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  echo ~/.ssh/pk
                  
                  # Debugging steps
                  echo "Contents of ~/.ssh directory:"
                  ls -la ~/.ssh
                  echo "Contents of known_hosts:"
                  cat ~/.ssh/known_hosts
#            - name: Test SSH connection
#              run: ssh -T git@github.com || exit 1
            - run: npm ci
            - run: npm run build
            - run: |
                  git config --global user.name 'Marc MOREAU'
                  git config --global user.email 'moreau.marc.web@gmail.comm'
            - run: git add . && git commit -m "clean" || echo "No changes to commit"
            - run: npm version patch
            - name: Configure Git to use SSH key
              run: |
                  git config core.sshCommand 'ssh -i ~/.ssh/pk -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
            - name: Push changes
              run: |
                  git remote set-url origin git@github.com:${{ github.repository }}.git
                  git push origin main --follow-tags
